version: "3"
services:
  grafana: # https://github.com/grafana/grafana
    restart: always
    image: grafana/grafana:10.0.8
    networks:
      - media-dashboard
    ports:
      - 3000:3000

  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-5
    restart: always
    networks:
      - media-dashboard
    ports:
      - 2003:2003
      #- 2004:2004
      #- 7002:7002
      #- 8125:8125/udp
      #- 8126:8126
      #- 8080:80
      - 8888:8080
    volumes:
      - ./graphite/storage:/opt/graphite/storage

networks:
  media-dashboard:
    driver: bridge

